version: '3'

services:
  app:
    image: healthcheck-api:latest
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: development
      DATABASE_URI: 'postgresql+psycopg2://postgres:postgres@rdb:5432/development'
      HTTPS_PROXY: ${HTTPS_PROXY}
  rdb:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: development
